apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cdjwnajca-nodejs 
  janus-idp.io/tekton: cdjwnajca-nodejs
  backstage.io/kubernetes-id: cdjwnajca-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cdjwnajca-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  